baseURL: "http://Kiyuu-o.github.io"
languageCode: "en-us"
title: "Kexuan Miao (缪可轩)"
theme: ["PaperMod"]
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Archive"
      url: "/archives/"
      weight: 2
    - name: "Search"
      url: "/search/"
      weight: 3
params:
  ShowReadingTime: true
  mode: "homeinfo"
  homeInfoParams:
    Title: "Hi there 👋"
    Content: |
      Welcome to my competitive programming blog! Here you'll find tutorials, solutions, and insights on problem-solving techniques.
      Feel free to explore the site and check out my archive for more articles!

  socialIcons: # Optional, if you want to add social icons
    - name: "Github"
      url: "https://github.com/kiyuu-o"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/kevin-miao-cs/"

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
